import{a as L,S as b,i as u}from"./assets/vendor-03da8548.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const n of r.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&s(n)}).observe(document,{childList:!0,subtree:!0});function i(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function s(e){if(e.ep)return;e.ep=!0;const r=i(e);fetch(e.href,r)}})();async function f(t,o){const s="https://pixabay.com/api/",e={key:"43041849-c8f652645a26d9036757deffe",q:t,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15,page:o};return(await L.get(s,{params:e})).data}function v(t){const{webformatURL:o,largeImageURL:i,tags:s,likes:e,views:r,comments:n,downloads:y}=t;return`<li class="modal">
          <a class="gallery-link" href="${o}">
            <img loading="lazy" class="gallery-image" src="${i}" data-source="${o}" alt="${s}">
          </a>
          <div class="div-info">
            <p class="p-info"><span class="p-span">Likes</span> ${e}</p>
            <p class="p-info"><span class="p-span">Views</span> ${r}</p>
            <p class="p-info"><span class="p-span">Coments</span> ${n}</p>
            <p class="p-info"><span class="p-span">Downloads</span> ${y}</p>
          </div>
        </li>`}function S(t){return t.map(v).join("")}const w=new b(".gallery a",{captionsData:"alt",captionDelay:250});function m(t){const o=S(t);d.insertAdjacentHTML("beforeend",o),w.refresh()}const d=document.querySelector(".gallery"),q=document.querySelector(".form"),c=document.querySelector(".loader"),p=document.querySelector(".load-more");let l,a=1,g=0;const $=15;q.addEventListener("submit",E);p.addEventListener("click",M);async function E(t){t.preventDefault(),d.innerHTML="",a=1;try{c.classList.remove("loader-hidden"),l=t.target.elements.query.value.trim();const o=await f(l,a);g=Math.ceil(o.totalHits/$),o.hits.length===0?u.error({position:"topRight",color:"blue",title:"Error",message:"Sorry, there are no images matching your search query. Please try again!"}):m(o.hits)}catch(o){console.log(o)}c.classList.add("loader-hidden"),h(),t.target.reset()}async function M(){a+=1,c.classList.remove("loader-hidden");try{const t=await f(l,a);m(t.hits)}catch(t){console.log(t)}A(),h(),c.classList.add("loader-hidden")}function P(){p.classList.remove("hidden")}function R(){p.classList.add("hidden")}function h(){a>=g?(R(),a>1&&u.error({position:"topRight",color:"blue",title:"Error",message:"We're sorry, but you've reached the end of search results."})):P()}function A(){const t=d.firstChild.getBoundingClientRect().height;scrollBy({top:t*3,behavior:"smooth"})}
//# sourceMappingURL=commonHelpers.js.map
