import{a as L,S,i as c}from"./assets/vendor-03da8548.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const i of o.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&s(i)}).observe(document,{childList:!0,subtree:!0});function n(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function s(e){if(e.ep)return;e.ep=!0;const o=n(e);fetch(e.href,o)}})();async function m(t,r){const s="https://pixabay.com/api/",e={key:"43041849-c8f652645a26d9036757deffe",q:t,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15,page:r};return(await L.get(s,{params:e})).data}function v(t){const{webformatURL:r,largeImageURL:n,tags:s,likes:e,views:o,comments:i,downloads:y}=t;return`<li class="modal">
          <a class="gallery-link" href="${r}">
            <img loading="lazy" class="gallery-image" src="${n}" data-source="${r}" alt="${s}">
          </a>
          <div class="div-info">
            <p class="p-info"><span class="p-span">Likes</span> ${e}</p>
            <p class="p-info"><span class="p-span">Views</span> ${o}</p>
            <p class="p-info"><span class="p-span">Coments</span> ${i}</p>
            <p class="p-info"><span class="p-span">Downloads</span> ${y}</p>
          </div>
        </li>`}function b(t){return t.map(v).join("")}const q=new S(".gallery a",{captionsData:"alt",captionDelay:250});function f(t){const r=b(t);p.insertAdjacentHTML("beforeend",r),q.refresh()}const p=document.querySelector(".gallery"),w=document.querySelector(".form"),l=document.querySelector(".loader"),u=document.querySelector(".load-more");let d,a=1,g=0;const E=15;w.addEventListener("submit",P);u.addEventListener("click",R);async function P(t){t.preventDefault(),p.innerHTML="",a=1;try{l.classList.remove("loader-hidden"),d=t.target.elements.query.value.trim();const r=await m(d,a);g=Math.ceil(r.totalHits/E),r.hits.length===0?c.error({position:"topRight",color:"red",title:"Error",message:"Sorry, there are no images matching your search query. Please try again!"}):f(r.hits)}catch{c.error({position:"topRight",color:"red",title:"Error",message:"Sorry, there are no images matching your search query. Please try again!"})}l.classList.add("loader-hidden"),h(),t.target.reset()}async function R(){a+=1,l.classList.remove("loader-hidden");try{const t=await m(d,a);f(t.hits)}catch{c.error({position:"topRight",color:"red",title:"Error",message:"Sorry, there are no images matching your search query. Please try again!"})}A(),h(),l.classList.add("loader-hidden")}function $(){u.classList.remove("hidden")}function M(){u.classList.add("hidden")}function h(){a>=g?(M(),a>1&&c.error({position:"topRight",color:"blue",title:"Error",message:"We're sorry, but you've reached the end of search results."})):$()}function A(){const t=p.firstChild.getBoundingClientRect().height;scrollBy({top:t*3,behavior:"smooth"})}
//# sourceMappingURL=commonHelpers.js.map
