import{a as y,S as L,i as v}from"./assets/vendor-03da8548.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))r(e);new MutationObserver(e=>{for(const s of e)if(s.type==="childList")for(const a of s.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&r(a)}).observe(document,{childList:!0,subtree:!0});function i(e){const s={};return e.integrity&&(s.integrity=e.integrity),e.referrerPolicy&&(s.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?s.credentials="include":e.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function r(e){if(e.ep)return;e.ep=!0;const s=i(e);fetch(e.href,s)}})();async function u(t,o){const r="https://pixabay.com/api/",e={key:"43041849-c8f652645a26d9036757deffe",q:t,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15,page:o};return(await y.get(r,{params:e})).data}function b(t){const{webformatURL:o,largeImageURL:i,tags:r,likes:e,views:s,comments:a,downloads:h}=t;return`<li class="modal">
          <a class="gallery-link" href="${o}">
            <img loading="lazy" class="gallery-image" src="${i}" data-source="${o}" alt="${r}">
          </a>
          <div class="div-info">
            <p class="p-info"><span class="p-span">Likes</span> ${e}</p>
            <p class="p-info"><span class="p-span">Views</span> ${s}</p>
            <p class="p-info"><span class="p-span">Coments</span> ${a}</p>
            <p class="p-info"><span class="p-span">Downloads</span> ${h}</p>
          </div>
        </li>`}function S(t){return t.map(b).join("")}const w=new L(".gallery a",{captionsData:"alt",captionDelay:250});function f(t){const o=S(t);d.insertAdjacentHTML("beforeend",o),w.refresh()}const d=document.querySelector(".gallery"),$=document.querySelector(".form"),c=document.querySelector(".loader"),p=document.querySelector(".load-more");let l,n=1,m=0;const q=15;$.addEventListener("submit",M);p.addEventListener("click",E);async function M(t){t.preventDefault(),d.innerHTML="",n=1;try{c.classList.remove("loader-hidden"),l=t.target.elements.query.value.trim();const o=await u(l,n);m=Math.ceil(o.totalHits/q),f(o.hits)}catch(o){console.log(o)}c.classList.add("loader-hidden"),g(),t.target.reset()}async function E(){n+=1,c.classList.remove("loader-hidden");try{const t=await u(l,n);f(t.hits)}catch(t){console.log(t)}P(),g(),c.classList.add("loader-hidden")}function A(){p.classList.remove("hidden")}function O(){p.classList.add("hidden")}function g(){n>=m?(O(),v.error({position:"topRight",color:"blue",title:"Error",message:"We're sorry, but you've reached the end of search results."})):A()}function P(){const t=d.firstChild.getBoundingClientRect().height;scrollBy({top:t*3,behavior:"smooth"})}
//# sourceMappingURL=commonHelpers.js.map
